DROP TABLE if exists  YG_USER;
DROP TABLE if exists  YG_DELIVERY;
DROP TABLE if exists  YG_DELIVERY_DETAIL;
DROP TABLE if exists  YG_VENDOR;
DROP TABLE if exists  YG_SYSTEM;

create table YG_USER (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	salt varchar(64) not null,
	roles varchar(255) not null,
	register_date timestamp not null,
	primary key (id)
);

CREATE TABLE YG_DELIVERY (
        ID bigint generated by default as identity,
        VENDOR_ID BIGINT NOT NULL,
        DELIVERY_NO VARCHAR(10) NOT NULL,
        DELIVERY_DATE TIMESTAMP NOT NULL,
        CREATE_USER BIGINT NOT NULL,
        CREATE_DATE TIMESTAMP NOT NULL,
        MODIFY_USER BIGINT,
        MODIFY_DATE TIMESTAMP,
        primary key (id)
    );
    
    CREATE TABLE YG_DELIVERY_DETAIL (
        ID bigint generated by default as identity,
        DELIVERY_ID VARCHAR(10) NOT NULL,
        NAME VARCHAR(128) NOT NULL,
        NUM INTEGER,
        PRICE DECIMAL(10 , 2),
        PROCEDURE VARCHAR(255),
        MEMO VARCHAR(255),
        primary key (id),
        FOREIGN KEY (DELIVERY_ID) REFERENCES YG_DELIVERY(ID)
    );
    
    CREATE TABLE YG_VENDOR (
        ID bigint generated by default as identity, 
        VENDOR_SNAME VARCHAR(20) NOT NULL,
        VENDOR_NAME VARCHAR(128) NOT NULL,
        VENDOR_TYPE VARCHAR(2),
        VENDOR_ADDRESS VARCHAR(128) ,
        VENDOR_PHONE VARCHAR(20) ,
        CREATE_USER BIGINT NOT NULL,
        CREATE_DATE TIMESTAMP NOT NULL,
        MODIFY_USER BIGINT,
        MODIFY_DATE TIMESTAMP,
        primary key (id)
    );

    CREATE TABLE YG_SYSTEM (
        ID bigint generated by default as identity,
        SYSTEM_CODE VARCHAR(50) NOT NULL,
        SYSTEM_NAME VARCHAR(50) NOT NULL,
        SYSTEM_VALUE VARCHAR(50) NOT NULL,
        primary key (id)
    );

